import { Metadata } from 'next';
import React, { FC } from 'react'

interface SignInPageProps{}

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
}
const SignInPage: FC<SignInPageProps> = ({ }) => {
  return (
    <div>
      SigninPage
    </div>
  )
}

export default SignInPage;